CREATE TABLE PRIVILEGE(
  PRIVILEGE_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(64),
  DESCRIPTION VARCHAR(64)
);

CREATE TABLE ROLE(
  ROLE_ID INTEGER PRIMARY KEY,
  NAME VARCHAR(64),
  DESCRIPTION VARCHAR(64)
);

CREATE TABLE ROLE_PRIVILEGES(
  ROLE_ROLE_ID INTEGER PRIMARY KEY,
  PRIVILEGES_PRIVILEGE_ID INTEGER
);

CREATE TABLE ACCOUNT(
  ID INTEGER PRIMARY KEY,
  ENABLED BIT,
  USERNAME VARCHAR(64),
  PASSWORD VARCHAR(64)
);

CREATE TABLE ACCOUNT_ROLES(
  ACCOUNT_ID INTEGER PRIMARY KEY,
  ROLES_ROLE_ID INTEGER
);